name: candlesticks
description: Sachiels AI Candlesticks

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  ####### ####### #######
  app_settings: ^6.1.1
  ####### ####### #######

  ####### ####### #######
  back_button_interceptor: ^8.0.4

  blur: ^4.0.2
  ####### ####### #######

  ####### ####### #######
  connectivity_plus: ^7.0.0

  cloud_firestore: ^6.0.3
  cloud_functions: ^6.0.3

  cupertino_icons: ^1.0.8

  currency_text_input_formatter: ^2.3.0
  ####### ####### #######

  ####### ####### #######
  firebase_core: ^4.2.0
  firebase_app_check: ^0.4.1+1

  firebase_analytics: ^12.0.3
  firebase_crashlytics: ^5.0.3

  firebase_auth: ^6.1.1

  firebase_database: ^12.0.3

  firebase_remote_config: ^6.1.0
  firebase_messaging: ^16.0.3
  firebase_in_app_messaging: ^0.9.0+3

  flutter_flip_card: ^0.0.6
  flutter_html: ^3.0.0

  flutter_phoenix: ^1.1.1
  flutter_slidable: ^4.0.3
  fluttertoast: ^8.2.14
  ####### ####### #######

  ####### ####### #######
  google_sign_in: ^6.3.0
  ####### ####### #######

  ####### ####### #######
  in_app_purchase: ^3.2.3
  in_app_purchase_android: ^0.4.0+5
  ####### ####### #######

  ####### ####### #######
  liquid_swipe: ^3.1.0
  loading_animation_widget: ^1.3.0
  local_auth: ^2.3.0
  ####### ####### #######

  ####### ####### #######
  marquee: ^2.2.3
  ####### ####### #######

  ####### ####### #######
  quick_actions: ^1.1.0
  ####### ####### #######

  ####### ####### #######
  permission_handler: ^12.0.1
  ####### ####### #######

  ####### ####### #######
  share_plus: ^12.0.1
  ####### ####### #######

  ####### ####### #######
  url_launcher: ^6.3.2
  ####### ####### #######

  ####### ####### #######
  widget_mask: ^1.0.0+0
  win32: ^5.15.0
  ####### ####### #######



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/ubuntu.ttf
    - family: Handwriting
      fonts:
        - asset: fonts/waterfall.ttf
    - family: Electric
      fonts:
        - asset: fonts/electric.ttf