name: candlesticks
description: Sachiels AI Candlesticks

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  ####### ####### #######
  app_settings: ^5.1.1
  ####### ####### #######

  ####### ####### #######
  back_button_interceptor: ^6.0.1

  blur: ^3.0.0
  ####### ####### #######

  ####### ####### #######
  connectivity_plus: ^5.0.2

  cloud_firestore: ^6.0.0
  cloud_functions: ^6.0.0

  cupertino_icons: ^1.0.5

  currency_text_input_formatter: ^2.1.7
  ####### ####### #######

  ####### ####### #######
  firebase_core: ^4.0.0
  firebase_app_check: ^0.4.0

  firebase_analytics: ^12.0.0
  firebase_crashlytics: ^5.0.0

  firebase_auth: ^6.0.1

  firebase_database: ^12.0.0

  firebase_remote_config: ^6.0.0
  firebase_messaging: ^16.0.0
  firebase_in_app_messaging: ^0.9.0

  flutter_flip_card: ^0.0.4
  flutter_html: ^3.0.0-beta.2

  flutter_phoenix: ^1.0.0
  flutter_slidable: ^2.0.0
  fluttertoast: ^8.0.9
  ####### ####### #######

  ####### ####### #######
  google_sign_in: ^6.2.1
  ####### ####### #######

  ####### ####### #######
  in_app_purchase: ^3.2.3
  in_app_purchase_android: ^0.4.0+2

  intl: ^0.17.0
  ####### ####### #######

  ####### ####### #######
  liquid_swipe: ^3.1.0
  loading_animation_widget:
    path: 'X:\Xlutter\Libraries\loading_animation_widget'
  local_auth: ^2.1.0
  ####### ####### #######

  ####### ####### #######
  marquee: ^2.2.3
  ####### ####### #######

  ####### ####### #######
  quick_actions: ^1.0.6
  ####### ####### #######

  ####### ####### #######
  permission_handler: ^12.0.1
  ####### ####### #######

  ####### ####### #######
  screenshot: ^3.0.0
  share_plus: ^11.0.0
  ####### ####### #######

  ####### ####### #######
  url_launcher: ^6.2.5
  ####### ####### #######

  ####### ####### #######
  webview_flutter: ^4.7.0
  widget_mask: ^1.0.0+0
  win32: ^5.10.1
  ####### ####### #######



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/ubuntu.ttf
    - family: Handwriting
      fonts:
        - asset: fonts/waterfall.ttf
    - family: Electric
      fonts:
        - asset: fonts/electric.ttf