name: candlesticks
description: Sachiels AI Candlesticks

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter



  ####### ####### #######
  app_settings: ^5.1.1
  ####### ####### #######



  ####### ####### #######
  back_button_interceptor: ^6.0.1

  blur: ^3.0.0
  ####### ####### #######



  ####### ####### #######
  connectivity_plus: ^5.0.2

  cloud_firestore: ^4.15.5
  cloud_functions: ^4.6.5

  cupertino_icons: ^1.0.5

  currency_text_input_formatter: ^2.1.7
  ####### ####### #######



  ####### ####### #######
  firebase_core: ^2.24.2
  firebase_app_check: ^0.2.1+8

  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.9

  firebase_auth: ^4.16.0

  firebase_database: ^10.2.7

  firebase_remote_config: ^4.3.8
  firebase_messaging: ^14.7.10
  firebase_in_app_messaging: ^0.7.4+8

  firebase_dynamic_links: ^5.4.8

  flutter_flip_card: ^0.0.4
  flutter_html:
    path: 'X:\Xlutter\Libraries\flutter_html'

  flutter_phoenix: ^1.0.0
  flutter_slidable: ^2.0.0
  ####### ####### #######



  ####### ####### #######
  google_sign_in: ^6.0.1
  ####### ####### #######



  ####### ####### #######
  in_app_purchase: ^3.1.10
  intl: ^0.17.0
  ####### ####### #######



  ####### ####### #######
  loading_animation_widget:
    path: 'X:\Xlutter\Libraries\loading_animation_widget'
  local_auth: ^2.1.0
  ####### ####### #######



  ####### ####### #######
  marquee: ^2.2.3
  ####### ####### #######



  ####### ####### #######
  quick_actions: ^1.0.6
  ####### ####### #######



  ####### ####### #######
  share_plus: ^7.2.2
  status_bar_control:
    path: 'X:\Xlutter\Libraries\flutter_statusbar_control'
  ####### ####### #######



  ####### ####### #######
  url_launcher: ^6.1.5
  ####### ####### #######



  ####### ####### #######
  webview_flutter: ^4.7.0
  widget_mask: ^1.0.0+0
  ####### ####### #######



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true

  assets:
    - assets/



  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/ubuntu.ttf
    - family: Handwriting
      fonts:
        - asset: fonts/waterfall.ttf
    - family: Electric
      fonts:
        - asset: fonts/electric.ttf



flutter_native_splash:
  color: "#000000"

  image: assets/logo.png

  branding: assets/logo.png

  branding_mode: center

  android_12:

  android: true
  ios: true
  web: false



flutter_icons:
  image_path_android: "assets/logo_android.png"
  image_path_ios: "assets/logo_ios.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/logo_background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/logo.png" #
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"



flutter_app_name:
  name: "Sachiels AI; Candlesticks"